### PR TITLE
Fix #40: Openshift changes

### LINKED ISSUE #40: Running in Openshift / Kubernetes fails
Hello,

when trying to run the container in Openshift / Kubernetes the container crashes because the security context in those platforms doesn't allow containers to run as root.

### PR DESCRIPTION
**Pull request by tobiasge**
With these modifications the resulting container can be run in
Openshift / Kubernetes. No more root privileges are needed.

### CODE REVIEW

**Comment by GuyShaanan** [comment]
Thank you so much for your contirubuiton.
I do have couple of questions regarding this change. Once sorted out I will be happy to merge it.

(I have no way to test it ATM under Openshift / Kubernetes, but I did test it under Docker and it works fine).

**Comment by tobiasge** [comment]
You can test this patch witch a local Openshift cluster. Just download the Openshift client tools from https://github.com/openshift/origin/releases and start it with "oc cluster up".

If you have further questions I'd be happy to answer them.

**Comment by mcdoker18** [comment]
Hi, I tested the changes in an Openshift 3.9. They look good for me.
@GuyShaanan  Any plans to merge?
@tobiasge How do you configure the readinessProbe and livenessProbe for Cloudflow?

**Comment by tobiasge** [comment]
Hello,

at the moment we are simply checking if the webserver is available. This is the configuration:

```yaml
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 8000
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 8000
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
```

Kind regards
Tobias

**Comment by mcdoker18** [comment]
@tobiasge Thanks for the quick response!

**Pull request merged**
