### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by mcdoker18**

### CODE REVIEW

**Comment by GuyShaanan** [comment]
Hi!
Thank you so much for your contribution.
Docker file can really speed up the evaluation of CloudFlow by new users.

I try to understand why the change in cloudflow.nginx.conf? The purpose of the current configuration is to allow running CloudFlow behind https, and listening on IPv6 addresses, which seems you've omitted.

Moreover, what we had in mind is bundling the Dockerfile in the output (the .tar.gz) file so users will not have to download and compile the source files (most of the users will download the .tar.gz file instead of cloning this repo).

We do like how simple and concise the Dockerfile is.
We will be happy to merge your PR once sorting the configuration issues.
Thanks again for your contribution!

**Comment by mcdoker18** [comment]
Hi.
Thank you for the Mistral UI. And sorry for long delay.
I add the ssl support to Docker image. Is it okay now?

I did not quite understand what you mean when you tell about the zip archive. Is it https://docs.docker.com/engine/reference/commandline/import/#extended-description ? I think the better idea to set some job which push image to the Docker registry after new release of CloudFlow.

**Comment by Sudhagar1985** [comment]
Hi.. Thanks for the wonderful Mistral UI . Its a great work!!!
Any idea if you have/know the UI for Mistral workflow design using a drag and drop feature.

**Comment by rakhmerov** [comment]
Hi! Thanks for your feedback!

No, currently there isn't an open source UI tool for building Mistral workflows. We might be implementing it in CloudFlow later but haven’t decided yet. We want to focus on read-only functionality for now and make it shine before switching to workflow builder.

Thanks

Renat Akhmerov
@Nokia

**Comment by Sudhagar1985** [comment]
Ok. Thanks for the update.

**Comment by andrask** [comment]
I'd really love to see this merge being done.

**Comment by mcdoker18** [comment]
@GuyShaanan please, take a look. I resolved the merge conflicts

**Comment by andrask** [comment]
Very good, thanks! I checked and builds perfectly. :100:  to merge it.

**Comment by andrask** [comment]
Hi @GuyShaanan, let me chime in for this PR:

1. Yes, I think the modified config file is significantly better than the original as it enables more automated configuration options which is a necessity for docker based testing/deployment.

2. In my original PR, I also built on the possibility to use the released artifacts. The basic issue is that the configuration is not supported for older versions and we have no idea how it is going to change in the future. I would much rather stick the container to the git repo and a given CloudFlow version. Having to build in corporate environments is always a pain but one has to find the way to do it any way. If they can't solve this issue, then we could provide an official DockerHub repo (supposedly with automated builds).

So all in all, I think this PR is as good as it can be.

**Comment by GuyShaanan** [comment]
@mcdoker18 Can you make a dedicated ngnix configuration file for the Docker (instead of editing the existing one) `cloudflow.docker.nginx.conf`? We will then merge your PR as it is really helpful contribution.

**Comment by mcdoker18** [comment]
@GuyShaanan Okay, no problem. I will do it in a few hour.

**Comment by mcdoker18** [comment]
@GuyShaanan  Done.
@andrask I fixed image to handle SIGTERM signal properly. Please, check

**Pull request merged**
